// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbSSvLNixv0OiYQ5_Z9ZUKlHXJgxP1wwo',
    appId: '1:90636321709:web:735008fdc742f1550b1724',
    messagingSenderId: '90636321709',
    projectId: 'anketdemo01',
    authDomain: 'anketdemo01.firebaseapp.com',
    storageBucket: 'anketdemo01.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpMogAdB0VtgZxcPvVQG9PKEvnn6lBSJ4',
    appId: '1:90636321709:android:0a22b0865244e20c0b1724',
    messagingSenderId: '90636321709',
    projectId: 'anketdemo01',
    storageBucket: 'anketdemo01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxTxOEji4r799LP9a7YfQlYhHRRxa4vjc',
    appId: '1:90636321709:ios:50b870b455a397a60b1724',
    messagingSenderId: '90636321709',
    projectId: 'anketdemo01',
    storageBucket: 'anketdemo01.appspot.com',
    iosBundleId: 'com.example.anketproje',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxTxOEji4r799LP9a7YfQlYhHRRxa4vjc',
    appId: '1:90636321709:ios:50b870b455a397a60b1724',
    messagingSenderId: '90636321709',
    projectId: 'anketdemo01',
    storageBucket: 'anketdemo01.appspot.com',
    iosBundleId: 'com.example.anketproje',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbSSvLNixv0OiYQ5_Z9ZUKlHXJgxP1wwo',
    appId: '1:90636321709:web:380f510ff016b7530b1724',
    messagingSenderId: '90636321709',
    projectId: 'anketdemo01',
    authDomain: 'anketdemo01.firebaseapp.com',
    storageBucket: 'anketdemo01.appspot.com',
  );
}
